### ISSUE TITLE
provider.cobbler: XML syntax error on line 13: element <meta> closed by </head>

### ISSUE THREAD

**Issue by etc-fstab** [terraform-providers/terraform-provider-cobbler#16] opened 2018-08-31 23:37 UTC
### Terraform Version
This is on Oracle Linux 7.5

#terraform -v
Terraform v0.11.8
and provider.cobbler v1.0.1

### Terraform Configuration Files
variable "cobbler_username" {default="xxx"}
variable "cobbler_password" {default="xxxx"}
variable "cobbler_url" {default="http://host.domain.com/cobbler_api"}

provider "cobbler" {
  username = "${var.cobbler_username}"
  password = "${var.cobbler_password}"
  url      = "${var.cobbler_url}"
  insecure = true
}

resource "cobbler_kickstart_file" "ks-zd-ol7" {
  name = "/var/lib/cobbler/kickstarts/ks-zd-ol7"
  body = <<-EOF
       my ks file
       EOF
}

### Debug Output
https://gist.github.com/zdudic/a57eeb649d6a7a8b6521879f4e6121cf

### Expected Behavior
There is no error for "terraform validate" and there is error for 'terraform plan" 

### Actual Behavior
This is 'terraform plan ' error: 
Error: Error running plan: 1 error(s) occurred:
provider.cobbler: XML syntax error on line 13: element <meta> closed by </head>

### Steps to Reproduce
Just create presented .tf file and run 'terraform plan'. 

### References
[](url)

**Comment by jtopjian** [comment] 2018-09-03 05:39
@zdudic Thanks for reporting the issue. However, I'm unable to reproduce the error you're reporting. This is the output I'm seeing:

```
$ cat main.tf 
resource "cobbler_kickstart_file" "ks-zd-ol7" {
  name = "/var/lib/cobbler/kickstarts/ks-zd-ol7"
  body = <<-EOF
    my ks file
    EOF
}

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + cobbler_kickstart_file.ks-zd-ol7
      id:   <computed>
      body: "my ks file\n"
      name: "/var/lib/cobbler/kickstarts/ks-zd-ol7"


Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Your debug output shows there's also a `cobbler_snippet` resource. Do you know if the contents of the snippet might be causing this issue?

**Comment by etc-fstab** [comment] 2018-09-04 17:56
Thanks Joe. I wasn't able to reproduce what you did, which leads me to suspect how a server talks to my cobbler machine. Using wireshark I saw message: "<some IP> -> <terraform IP> HTTP 1601 HTTP/1.1 502 notresolvable  (text/html)", and I found that "some IP" was exported shell valuable "http_proxy".  After it was unset, all works well. Thanks again.

**Comment by jtopjian** [comment] 2018-09-05 01:51
@zdudic Glad to hear! 

I'm going to close this issue but let me know if you have any other questions.

**Closed as completed by jtopjian** 2018-09-05 01:51 UTC
